### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/redux-elm-middleware#12]
Would be awesome, but I'm not really good at it. 
Idea:
r.e.m (eye and a elm tree within)

**Comment by scottcorgan** [comment]
Probably just overlaying the [Redux Logo](https://github.com/reactjs/redux/blob/master/logo/README.md) with the [Elm logo](https://avatars0.githubusercontent.com/u/4359353?v=3&s=280) ([Like the Elm User Group SF logo](http://www.meetup.com/Elm-user-group-SF/))

(It's not my specialty, but here the images for reference)

![687474703a2f2f692e696d6775722e636f6d2f4a65567164514d2e706e67](https://cloud.githubusercontent.com/assets/974723/15288875/0b629c0c-1b3c-11e6-9113-2d033210f840.png)

![4359353](https://cloud.githubusercontent.com/assets/974723/15288882/16d43f00-1b3c-11e6-9c1b-b09f32262d2e.png)

![global_449674287](https://cloud.githubusercontent.com/assets/974723/15288854/fb910b60-1b3b-11e6-91a9-69edc9a24b0f.png)

**Comment by sectore** [comment]
![image](https://cloud.githubusercontent.com/assets/47693/15298302/e3cf3a52-1b9e-11e6-95ac-68026bcdb500.png)

Idea: This logo is similar to Redux' logo, but with one more line. The extra line means: Hey, that's Redux with an extra cool thing. All colors are Elm colors of course ;)

**Comment by stoeffel** [comment]
This is awesome! Let's go with it. Thanks a lot. Will you add it to the
readme in the v0.17 branch?

**Comment by sectore** [comment]
I'm going to create a folder `logo` in this repo (branch `v0.17`) and upload the logo in different formats (`svg`, `png`). Also in 300dpi, just in case to print some stickers later on ;)
