### ISSUE TITLE
action type to lowercase 

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/redux-elm-middleware#13]
Currently you have to dispatch actions in on the redux star with the same type as the port in the elm reducer.

``` js
store.dispatch({type:"increment"})
```

``` elm
port increment : Maybe Int -> Cmd Msg
```

The problem with this is that it's common in redux to have uppercased action types.
I propose, that r.e.m should `.toLowerCase` to match the action type and the port.

**Comment by stoeffel** [comment]
better use https://github.com/sindresorhus/camelcase for this.

**Comment by bipvanwinkle** [comment]
https://github.com/sindresorhus/camelcase converts things like "foor bar" to fooBar. I don't think this is what we need, right? 

Elm ports will sometime be camelcase. Could we convert (just for the equality check) the elm ports to lowercase and compare them with the lowercase version of the action type. 

I think it could be pretty tricky to convert "ActionType" to "actionType".

**Comment by stoeffel** [comment]
we need to match `MY_ACTION` (redux) to myAction (elm port).
I think, if we camelcase(reduxAction) then it should equal the port.

**Comment by bipvanwinkle** [comment]
Gotcha, you're right then. Using https://github.com/sindresorhus/camelcase should do the trick. I'll get working on it and put in a pull request.

**Comment by stoeffel** [comment]
awesome!
