### ISSUE TITLE
better docs

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/redux-elm-middleware#14]
use gitbook

**Comment by bipvanwinkle** [comment]
How do you want to start this? What would you like to document?

**Comment by stoeffel** [comment]
- [ ] The public api of `Redux.elm` should be documented like http://package.elm-lang.org/packages/elm-lang/html/1.0.0/Html-App#program
- [ ] same for the api of the redux middleware.
- [ ] maybe a diagram of the flow would be nice
- [ ] move motivation to it's own file
- [ ] describe how to encode the outgoing model

It would be nice if the api is in `API.md` and the readme reads like a getting started (step-by-step) guide.

What do you think?

**Comment by bipvanwinkle** [comment]
Looks good to me. I'll see what I can do over the next few days to get this started.
