### ISSUE TITLE
Hide ports from user

### ISSUE THREAD

**Issue by jwoudenberg** [stoeffel/redux-elm-middleware#2]
It would be nice if the user doesn't have to wire both parts of the app together explicitly. On the JS side, perhaps the `elmStore` initialization could happen inside the `createElmMiddleware` function? And on the Elm side, perhaps we can have a modifies startApp that does away with the views (not needed right?) and sets up the port connection by defaults?

Instead, perhaps we can simply pass an array of action types that the elm middleware should handle.

**Comment by stoeffel** [comment]
SGTM. Was playing with a custom startapp, but didn't continue atm. Take care startapp is not MIT licensed.

**Comment by stoeffel** [comment]
We could add a `StartStore.simple` which takes care of everything (ports, mergeMany,...)

**Comment by stoeffel** [comment]
``` elm
reducer =
  StartReducer.start
    { init = init 0
    , update = update
    , actions = actions
    }

```

**Comment by stoeffel** [comment]
One thing. `events = Signal.mergeMany(...)` allows the user to do some nice things like filtering signals, dropingRepeats and so on. in most cases this won't be necessary. So I propose to create a StartReducer.simple and a not simple one like StartApp.

**Comment by stoeffel** [comment]
Okay. Hidding away the input ports is not a good option imo.
Because you want StartReducer to handle other inputs as well like a ticker or something else. But we can hide the out port and remove the unnecessary dep to html for the view

**Comment by stoeffel** [comment]
There is more boilerplate with elm 0.17 see #9.
IMO we should create an elm-package.

``` elm
Reducer.program(
  { init = init
  , update = update
  , subscriptions = subscriptions
  })
```

cc @sectore
