### ISSUE TITLE
fallback until this is published to the elm repo

### ISSUE THREAD

**Issue by stoeffel** [stoeffel/redux-elm-middleware#21]
change `var _stoeffel$redux_elm_middleware$Native_Redux = function() {`
into `var _stoeffel$redux_elm_middleware$Native_Redux = _user$project$Native_Redux  = function() {`

cc @Bipsy

**Comment by stoeffel** [comment]
probably won't work. maybe just publishing elm-package.json to npm works. will try tomorrow.

**Comment by bipvanwinkle** [comment]
You're fine. Thanks so much for taking a look.
