### ISSUE TITLE
ELM 0.18 upgrade

### ISSUE THREAD

**Issue by kalutheo** [stoeffel/redux-elm-middleware#63]
Have you planned to upgrade to ELM 0.18 ?
Thanks for Your amazing work !

**Comment by stoeffel** [comment]
as soon as I have time. but maybe someone wants to contribute!

**Comment by kalutheo** [comment]
Yes i understand !Will try to contribute if i have Time too. Thanks for your quick reply !

**Comment by stoeffel** [comment]
that would be awesome ❤️

**Comment by kalutheo** [comment]
Hi there, i did a try to upgrade to 0.18.
I forked the repo and managed to make it compile to 0.18.
However, i didn't manage to make your example work with elm-live.
You can have a look here : 

https://github.com/kalutheo/redux-elm-middleware/commits/v018

I managed to use it in a side project in 0.18.

Hope it can help you for the migration 😄

**Comment by kalutheo** [comment]
After running `npm run example` and visiting 127.0.0.1:8080 i have the following error : 

<img width="1022" alt="capture d ecran 2016-12-05 a 22 21 26" src="https://cloud.githubusercontent.com/assets/15056358/20902879/68b471b2-bb39-11e6-80e4-334a97c80222.png">

**Comment by stoeffel** [comment]
It works for me 💭 did you remove node_modules and run `npm install` first? maybe install `npm install elm@0.17 -g`

**Comment by theocar** [comment]
yep i removed node_modules, then ran `npm install` then `npm run example` . Everything builds as expected. Then i visit 127.0.0.1:8080. I still have the issue. I checked my elm version installed globally , it's 0.18 and the elm version in the package.json as well.
Did you run other commands to make it work ? Why should i run `npm install elm@0.17 -g`,  we want to move to 0.18 right ?

**Comment by stoeffel** [comment]
Haha. I thought you tried yo run it first with 0.17

**Comment by stoeffel** [comment]
will look into your branch

**Comment by theocar** [comment]
cool thanks 😸

**Comment by stoeffel** [comment]
@kalutheo no thank you!!!

Okay solved it. Two things need to change:

1. we need to require the compiled elm reducer. It's not global (on `window`) anymore.
```diff
// examples/src/index.js
+ import Elm from '../build/elm'
- const elmStore = window.Elm.Reducer.worker();
+ const elmStore = Elm.Reducer.worker();
```

2. the signature of the incoming ports is invalid:

```diff
-- examples/src/Reducer.elm
+ import Json.Decode exposing (Value)
- port increment : ({} -> msg) -> Sub msg
+ port increment : (Value -> msg) -> Sub msg
- port asyncIncrement : ({} -> msg) -> Sub msg
+ port asyncIncrement : (Value -> msg) -> Sub msg
- port asyncDecrement : ({} -> msg) -> Sub msg
+ port asyncDecrement : (Value -> msg) -> Sub msg
- port decrement : ({} -> msg) -> Sub msg
+ port decrement : (Value -> msg) -> Sub msg
port changeCount : (Payload -> msg) -> Sub msg -- <= this still works

```

**Comment by theocar** [comment]
Great ! Should i make a PR to your main repo ?

**Comment by stoeffel** [comment]
@theocar yes, please!

**Comment by kalutheo** [comment]
Here we go ! https://github.com/stoeffel/redux-elm-middleware/pull/64

**Comment by stoeffel** [comment]
cool!!! will review and publish tomorrow.

**Comment by ahstro** [comment]
What happened to this? :)

**Comment by stoeffel** [comment]
Published. I'm sorry, totally forgot about this.
